image: etna/drone-php
env:
  - APPLICATION_ENV=drone
  - COVERALLS_REPO_TOKEN=$$COVERALLS_TOKEN
  - COVERALLS_SERVICE_NAME=drone.io
script:
  - composer install --dev --no-interaction --prefer-source
  - composer phing
  - composer coveralls
notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: drone
    channel: $$SLACK_CHANNEL
    on_started: true
    on_failure: true
    on_success: true
